### ISSUE TITLE
When you Open the Order Menu

### ISSUE THREAD

**Issue by LySoon** [stianhje/sawu_hookers#2]
You can't close it or you can't move even after you restart the whole resource ^^

**Comment by LySoon** [comment]
Also found out now, hooker won't get in the car

**Comment by stianhje** [comment]
Do you have mythic_notify running?

**Comment by LySoon** [comment]
Yea, might be a lil older version..

So i have changed mythic_notify events bymyself and Resource is working properly right now.

You have done a Excellent job ^^ i really love it.

Like you even done sounds its so cool.


But im trying to do something more 
Like this : 


RegisterNUICallback("ChooseSex", function (data, callback)
    SetNuiFocus(false, false)
    callback("ok")
    HookerInCar = false
    TriggerServerEvent("sawu_hookers:pay", false)
    TriggerServerEvent('esx_society:depositMoney', nightclub, 500)
end)

İt gives errors.. i have changed all hooker spawn points to Strip club and pimp in to club too.. and i want to add society money when players use girls ^^ 

Can you help me about it ? 
İ have asked it to esx discord.. but no respo se..

**Comment by stianhje** [comment]
Download the latest release. Added support for society nightclub in the config. Set it to true if you want to use that. :)

Config.SocietyNightclub	= false -- Set to true if you want the money players pay to into the nightclub society account
