### ISSUE TITLE
İf some one picks a hooker

### ISSUE THREAD

**Issue by LySoon** [stianhje/sawu_hookers#3]
You can't pick another one for yourself.

for example : 

my friend was trying the resource

and i wanted to try too.. but i was un able to get her..

tried it several times but its same

**Comment by LySoon** [comment]
7nd time it worked. 

we tried it differently

Me picked the hooker to the car

after me my friend picked a hooker and it worked.

just wanted to let you know ^^

**Comment by stianhje** [comment]
Will look into it

**Comment by stianhje** [comment]
Have tryed with several people on the server and can not trigger your problem at all. Try to pull the latest build from github and get back to me if you still have the same problem. Make sure you have the latest version of mythic_notify running.
